[tool]
id = "health"

[[dependency]]
path = "resources/health-tools-0.1.0.jar"
# path = "resources/health-tools-0.1.0-jar-with-dependencies.jar"

# [[dependency]]
# path = "resources/tool-lib/healthcare-codegen-tool-common-3.1.0-SNAPSHOT.jar"

# [[dependency]]
# path = "resources/tool-lib/open-healthcare-fhir-tool-lib-3.1.0-SNAPSHOT.jar"

[[dependency]]
path = "resources/tool-lib/org.hl7.fhir.r4-4.2.0.jar"
[[dependency]]
path = "resources/tool-lib/javax.annotation-api-1.3.2.jar"
[[dependency]]
path = "resources/tool-lib/snakeyaml-1.26.jar"
[[dependency]]
path = "resources/tool-lib/commons-logging-1.2.jar"
[[dependency]]
path = "resources/tool-lib/toml4j-0.7.2.jar"
[[dependency]]
path = "resources/tool-lib/hapi-fhir-structures-r4-4.2.0.jar"
[[dependency]]
path = "resources/tool-lib/maven-builder-support-3.6.3.jar"
[[dependency]]
path = "resources/tool-lib/commons-io-2.7.jar"
[[dependency]]
path = "resources/tool-lib/testerina-runtime-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/javax.inject-1.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-api-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/ballerina-parser-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/xpp3_xpath-1.1.4c.jar"
[[dependency]]
path = "resources/tool-lib/ballerina-lang-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/commons-lang3-3.9.jar"
[[dependency]]
path = "resources/tool-lib/jsr305-3.0.2.jar"
[[dependency]]
path = "resources/tool-lib/opentelemetry-api-1.0.0.jar"
[[dependency]]
path = "resources/tool-lib/plexus-utils-3.2.1.jar"
[[dependency]]
path = "resources/tool-lib/asm-analysis-7.2.jar"
[[dependency]]
path = "resources/tool-lib/asm-tree-7.2.jar"
[[dependency]]
path = "resources/tool-lib/junit-4.12.jar"
[[dependency]]
path = "resources/tool-lib/okio-2.2.2.jar"
[[dependency]]
path = "resources/tool-lib/org.hl7.fhir.utilities-4.2.0.jar"
[[dependency]]
path = "resources/tool-lib/asm-7.2.jar"
[[dependency]]
path = "resources/tool-lib/woodstox-core-6.2.8.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-provider-3.6.3.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-named-locks-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/ucum-1.0.2.jar"
[[dependency]]
path = "resources/tool-lib/kotlin-stdlib-common-1.2.60.jar"
[[dependency]]
path = "resources/tool-lib/shell-cli-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/commons-codec-1.12.jar"
[[dependency]]
path = "resources/tool-lib/shell-core-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/checker-qual-2.8.1.jar"
[[dependency]]
path = "resources/tool-lib/hapi-fhir-structures-dstu2-4.2.0.jar"
[[dependency]]
path = "resources/tool-lib/maven-repository-metadata-3.6.3.jar"
[[dependency]]
path = "resources/tool-lib/picocli-4.0.1.jar"
[[dependency]]
path = "resources/tool-lib/plexus-interpolation-1.25.jar"
[[dependency]]
path = "resources/tool-lib/testerina-compiler-plugin-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/httpclient-4.5.13.jar"
[[dependency]]
path = "resources/tool-lib/cava-toml-0.5.0.jar"
[[dependency]]
path = "resources/tool-lib/jcommander-1.72.jar"
[[dependency]]
path = "resources/tool-lib/slf4j-api-1.7.26.jar"
[[dependency]]
path = "resources/tool-lib/guava-28.0-jre.jar"
[[dependency]]
path = "resources/tool-lib/shell-rt-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/java-semver-0.9.0.jar"
[[dependency]]
path = "resources/tool-lib/animal-sniffer-annotations-1.17.jar"
[[dependency]]
path = "resources/tool-lib/jcl-over-slf4j-1.7.28.jar"
[[dependency]]
path = "resources/tool-lib/netty-buffer-4.1.77.Final.jar"
[[dependency]]
path = "resources/tool-lib/atomikos-util-5.0.8.jar"
[[dependency]]
path = "resources/tool-lib/netty-common-4.1.77.Final.jar"
[[dependency]]
path = "resources/tool-lib/jakarta.activation-api-1.2.2.jar"
[[dependency]]
path = "resources/tool-lib/bsh-2.0b6.jar"
[[dependency]]
path = "resources/tool-lib/antlr4-runtime-4.7.1.jar"
[[dependency]]
path = "resources/tool-lib/ballerina-cli-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/commons-compress-1.21.jar"
[[dependency]]
path = "resources/tool-lib/testerina-core-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/hapi-fhir-base-4.2.0.jar"
[[dependency]]
path = "resources/tool-lib/transactions-api-5.0.8.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-transport-file-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/commons-collections-3.2.1.jar"
[[dependency]]
path = "resources/tool-lib/maven-artifact-3.6.3.jar"
[[dependency]]
path = "resources/tool-lib/commons-text-1.10.0.jar"
[[dependency]]
path = "resources/tool-lib/jline-3.11.0.jar"
[[dependency]]
path = "resources/tool-lib/failureaccess-1.0.1.jar"
[[dependency]]
path = "resources/tool-lib/asm-commons-7.2.jar"
[[dependency]]
path = "resources/tool-lib/identifier-util-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-connector-basic-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/javax.transaction-api-1.3.jar"
[[dependency]]
path = "resources/tool-lib/jballerina.java-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/xpp3-1.1.4c.jar"
[[dependency]]
path = "resources/tool-lib/docerina-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/progressbar-0.7.4.jar"
[[dependency]]
path = "resources/tool-lib/axiom-impl-1.4.0.jar"
[[dependency]]
path = "resources/tool-lib/axiom-api-1.4.0.jar"
[[dependency]]
path = "resources/tool-lib/opentelemetry-context-1.0.0.jar"
[[dependency]]
path = "resources/tool-lib/testng-6.14.3.jar"
[[dependency]]
path = "resources/tool-lib/toml-parser-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/java-diff-utils-4.5.jar"
[[dependency]]
path = "resources/tool-lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-util-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-impl-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/velocity-1.6.jar"
[[dependency]]
path = "resources/tool-lib/maven-model-3.6.3.jar"
[[dependency]]
path = "resources/tool-lib/stax2-api-4.2.1.jar"
[[dependency]]
path = "resources/tool-lib/commons-lang-2.4.jar"
[[dependency]]
path = "resources/tool-lib/open-healthcare-fhir-tool-lib-3.1.0-SNAPSHOT.jar"
[[dependency]]
path = "resources/tool-lib/annotations-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/org.eclipse.sisu.inject-0.3.4.jar"
[[dependency]]
path = "resources/tool-lib/oro-2.0.8.jar"
[[dependency]]
path = "resources/tool-lib/error_prone_annotations-2.3.2.jar"
[[dependency]]
path = "resources/tool-lib/j2objc-annotations-1.3.jar"
[[dependency]]
path = "resources/tool-lib/compiler-0.8.9.jar"
[[dependency]]
path = "resources/tool-lib/kotlin-stdlib-1.2.60.jar"
[[dependency]]
path = "resources/tool-lib/jansi-1.18.jar"
[[dependency]]
path = "resources/tool-lib/gson-2.8.9.jar"
[[dependency]]
path = "resources/tool-lib/annotations-13.0.jar"
[[dependency]]
path = "resources/tool-lib/central-client-2201.5.0.jar"
[[dependency]]
path = "resources/tool-lib/healthcare-codegen-tool-common-3.1.0-SNAPSHOT.jar"
[[dependency]]
path = "resources/tool-lib/fhir-ballerina-project-gen-tool-3.1.0-SNAPSHOT.jar"
[[dependency]]
path = "resources/tool-lib/ballerina-fhir-package-gen-tool-3.1.0-SNAPSHOT.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-transport-http-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/transactions-jta-5.0.8.jar"
[[dependency]]
path = "resources/tool-lib/maven-resolver-spi-1.7.0.jar"
[[dependency]]
path = "resources/tool-lib/maven-model-builder-3.6.3.jar"
[[dependency]]
path = "resources/tool-lib/httpcore-4.4.14.jar"
[[dependency]]
path = "resources/tool-lib/org.jacoco.core-0.8.5.jar"
[[dependency]]
path = "resources/tool-lib/apache-mime4j-core-0.8.6.jar"
[[dependency]]
path = "resources/tool-lib/org.jacoco.report-0.8.5.jar"
[[dependency]]
path = "resources/tool-lib/transactions-5.0.8.jar"
[[dependency]]
path = "resources/tool-lib/okhttp-3.14.0.jar"
[[dependency]]
path = "resources/tool-lib/fhir_client_connectorGen-1.0-SNAPSHOT.jar"
